In [1]:
import subprocess
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
import pandas as pd
import time
import os

In [2]:
epochs = 300
alpha = 0.1
HADOOP_PATH = '/LogReg'
INPUT_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/train.csv'
MAPPER_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py'
REDUCER_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py'
STREAMING_JAR = '/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.0.jar'

In [3]:
train_data = pd.read_csv('../train.csv', header=None)
X_train = train_data.iloc[: , :-1].to_numpy()
y_train = train_data.iloc[: , -1].to_numpy().reshape(-1,1)
print(X_train.shape)
print(y_train.shape)

(81298, 32)
(81298, 1)


In [4]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost(y, yhat):
    cost = -(y*np.log(yhat) + (1-y)*log(1-yhat))
    return cost

In [5]:
X_train_aug = np.pad(X_train, [(0,0), (1,0)], mode='constant', constant_values=1)
print(X_train_aug.shape)

(81298, 33)


In [6]:
w = np.zeros((X_train_aug.shape[1], 1))
print(w.shape)

(33, 1)


In [7]:
# for epoch in range(epochs):
#     for i in range(X_train.shape[0]):
#         x = np.insert(X_train[i], 0, 1).reshape(-1,1)
#         y = y_train[i]
        
#         yhat = sigmoid(w.T @ x).squeeze()
#         grad = (yhat - y) * x
#         w = w - alpha * grad

In [8]:
print(w)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
probs = X_train_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
print(predictions.shape)

(81298, 1)


In [10]:
acc_lr = accuracy_score(y_train, predictions)
conf = confusion_matrix(y_train, predictions)
clf_report = classification_report(y_train, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.6335826219587197
Confusion Matrix : 
[[51509     0]
 [29789     0]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.63      1.00      0.78     51509
           1       0.00      0.00      0.00     29789

    accuracy                           0.63     81298
   macro avg       0.32      0.50      0.39     81298
weighted avg       0.40      0.63      0.49     81298



/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
test_data = pd.read_csv('../test.csv', header=None)
X_test = test_data.iloc[: , :-1].to_numpy()
y_test = test_data.iloc[: , -1].to_numpy().reshape(-1,1)
print(X_test.shape)
print(y_test.shape)

(34842, 32)
(34842, 1)


In [12]:
X_test_aug = np.pad(X_test, [(0,0), (1,0)], mode='constant', constant_values=1)
print(X_test_aug.shape)
probs = X_test_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
print(predictions.shape)

(34842, 33)
(34842, 1)


In [13]:
acc_lr = accuracy_score(y_test, predictions)
conf = confusion_matrix(y_test, predictions)
clf_report = classification_report(y_test, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.6312496412375869
Confusion Matrix : 
[[21994     0]
 [12848     0]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.63      1.00      0.77     21994
           1       0.00      0.00      0.00     12848

    accuracy                           0.63     34842
   macro avg       0.32      0.50      0.39     34842
weighted avg       0.40      0.63      0.49     34842



/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
subprocess.run(["hdfs", "dfs", "-rm", "-r", HADOOP_PATH])
subprocess.run(["hdfs", "dfs", "-mkdir", HADOOP_PATH])
subprocess.run(["hdfs", "dfs", "-mkdir", f'{HADOOP_PATH}/Input'])
subprocess.run(["hdfs", "dfs", "-put", INPUT_PATH, f'{HADOOP_PATH}/Input'])

2022-05-06 16:15:02,478 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Deleted /LogReg


2022-05-06 16:15:03,512 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-06 16:15:04,571 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-06 16:15:05,749 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


CompletedProcess(args=['hdfs', 'dfs', '-put', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/train.csv', '/LogReg/Input'], returncode=0)

In [15]:
subprocess.run(["hdfs", "dfs", "-rm", "-r", f'{HADOOP_PATH}/Output'])

subprocess.run(
    [
        "hadoop",
        "jar", 
        STREAMING_JAR,
        "-file",
        MAPPER_PATH,
        "-file",
        REDUCER_PATH,
        "-input",
        f'{HADOOP_PATH}/Input',
        "-output",
        f'{HADOOP_PATH}/Output',
        "-mapper",
        f'{MAPPER_PATH} {epochs} {alpha}',
        "-reducer",
        f'{REDUCER_PATH}'
    ]
)

2022-05-06 16:15:07,175 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
rm: `/LogReg/Output': No such file or directory
2022-05-06 16:15:08,129 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
2022-05-06 16:15:08,207 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


packageJobJar: [/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py, /home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py, /tmp/hadoop-unjar4333037623252808435/] [] /tmp/streamjob63553551471458439.jar tmpDir=null


2022-05-06 16:15:08,675 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
2022-05-06 16:15:08,774 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
2022-05-06 16:15:08,904 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/islamahmed1092/.staging/job_1651835008910_0025
2022-05-06 16:15:09,078 INFO mapred.FileInputFormat: Total input files to process : 1
2022-05-06 16:15:09,107 INFO mapreduce.JobSubmitter: number of splits:2
2022-05-06 16:15:09,230 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1651835008910_0025
2022-05-06 16:15:09,230 INFO mapreduce.JobSubmitter: Executing with tokens: []
2022-05-06 16:15:09,366 INFO conf.Configuration: resource-types.xml not found
2022-05-06 16:15:09,366 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2022-05-06 16:15:09,408 INFO impl.YarnClientImpl: Submitted application application_165

CompletedProcess(args=['hadoop', 'jar', '/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.0.jar', '-file', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py', '-file', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py', '-input', '/LogReg/Input', '-output', '/LogReg/Output', '-mapper', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py 300 0.1', '-reducer', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py'], returncode=0)

In [16]:
subprocess.run(["hdfs", "dfs", "-cat", f'{HADOOP_PATH}/Output/*'])

2022-05-06 16:17:02,411 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


0,15.037025481178684	
1,0.1202704005243329	
10,0.08187539578836955	
11,-0.5134501636996455	
12,0.18984711662878367	
13,1.1455254246772375	
14,0.2906992399269484	
15,-0.09932190380252724	
16,-0.20833487464954736	
17,0.43522320602086234	
18,-1.616987385892193	
19,-0.26184998498099654	
2,-0.0237854661799455	
20,0.3260857058482226	
21,-0.4766494083753955	
22,1.1881137579022263	
23,0.020485637387636972	
24,-0.1520372939923933	
25,-0.37259135303694146	
26,-0.03183521502208818	
27,0.1515385730898184	
28,-8.320479365039638	
29,-0.29097197459798485	
3,188.13557228174923	
30,-187.98086621654056	
31,-72.67207978109818	
32,-6.254174261692578	
4,0.455439187169039	
5,67.90975995224385	
6,0.15296573232349117	
7,-0.22142059726957508	
8,1.1164417959223538	
9,-0.23995230771507858	


CompletedProcess(args=['hdfs', 'dfs', '-cat', '/LogReg/Output/*'], returncode=0)

In [17]:
subprocess.run(["rm", "-r", f'{os.getcwd()}/Output'])
subprocess.run(["hdfs", "dfs", "-get", f'{HADOOP_PATH}/Output/', os.getcwd()])

subprocess.run(["ls", 'Output'])

2022-05-06 16:17:03,700 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


part-00000
_SUCCESS


CompletedProcess(args=['ls', 'Output'], returncode=0)

In [18]:
out = pd.read_csv('Output/part-00000', header=None, names=["index", "w"])
out = out.sort_values('index').reset_index(drop=True)
out.head()

index           w
0      0   15.037025
1      1    0.120270
2      2   -0.023785
3      3  188.135572
4      4    0.455439

In [19]:
w = out['w'].to_numpy().reshape(-1, 1)
print(w.shape)

(33, 1)


In [20]:
probs = X_test_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
acc_lr = accuracy_score(y_test, predictions)
conf = confusion_matrix(y_test, predictions)
clf_report = classification_report(y_test, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.9675104758624649
Confusion Matrix : 
[[21875   119]
 [ 1013 11835]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.96      0.99      0.97     21994
           1       0.99      0.92      0.95     12848

    accuracy                           0.97     34842
   macro avg       0.97      0.96      0.96     34842
weighted avg       0.97      0.97      0.97     34842

