In [1]:
import subprocess
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
import pandas as pd
import time
import os

In [2]:
epochs = 100
alpha = 0.001
HADOOP_PATH = '/LogReg'
INPUT_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/train.csv'
MAPPER_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py'
REDUCER_PATH = '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py'
STREAMING_JAR = '/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.0.jar'

In [3]:
train_data = pd.read_csv('../train.csv', header=None)
X_train = train_data.iloc[: , :-1].to_numpy()
y_train = train_data.iloc[: , -1].to_numpy().reshape(-1,1)
print(X_train.shape)
print(y_train.shape)

(81298, 29)
(81298, 1)


In [4]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost(y, yhat):
    cost = -(y*np.log(yhat) + (1-y)*log(1-yhat))
    return cost

In [5]:
X_train_aug = np.pad(X_train, [(0,0), (1,0)], mode='constant', constant_values=1)
print(X_train_aug.shape)

(81298, 30)


In [6]:
w = np.zeros((X_train_aug.shape[1], 1))
print(w.shape)

(30, 1)


In [7]:
# for epoch in range(epochs):
#     for i in range(X_train.shape[0]):
#         x = np.insert(X_train[i], 0, 1).reshape(-1,1)
#         y = y_train[i]
        
#         yhat = sigmoid(w.T @ x).squeeze()
#         grad = (yhat - y) * x
#         w = w - alpha * grad

In [8]:
print(w)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
probs = X_train_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
print(predictions.shape)

(81298, 1)


In [10]:
acc_lr = accuracy_score(y_train, predictions)
conf = confusion_matrix(y_train, predictions)
clf_report = classification_report(y_train, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.6316883564171321
Confusion Matrix : 
[[51355     0]
 [29943     0]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.63      1.00      0.77     51355
           1       0.00      0.00      0.00     29943

    accuracy                           0.63     81298
   macro avg       0.32      0.50      0.39     81298
weighted avg       0.40      0.63      0.49     81298



/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
test_data = pd.read_csv('../test.csv', header=None)
X_test = test_data.iloc[: , :-1].to_numpy()
y_test = test_data.iloc[: , -1].to_numpy().reshape(-1,1)
print(X_test.shape)
print(y_test.shape)

(34842, 29)
(34842, 1)


In [12]:
X_test_aug = np.pad(X_test, [(0,0), (1,0)], mode='constant', constant_values=1)
print(X_test_aug.shape)
probs = X_test_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
print(predictions.shape)

(34842, 30)
(34842, 1)


In [13]:
acc_lr = accuracy_score(y_test, predictions)
conf = confusion_matrix(y_test, predictions)
clf_report = classification_report(y_test, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.6356695941679582
Confusion Matrix : 
[[22148     0]
 [12694     0]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.64      1.00      0.78     22148
           1       0.00      0.00      0.00     12694

    accuracy                           0.64     34842
   macro avg       0.32      0.50      0.39     34842
weighted avg       0.40      0.64      0.49     34842



/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/islamahmed1092/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
subprocess.run(["hdfs", "dfs", "-rm", "-r", HADOOP_PATH])
subprocess.run(["hdfs", "dfs", "-mkdir", HADOOP_PATH])
subprocess.run(["hdfs", "dfs", "-mkdir", f'{HADOOP_PATH}/Input'])
subprocess.run(["hdfs", "dfs", "-put", INPUT_PATH, f'{HADOOP_PATH}/Input'])

2022-05-06 14:15:07,331 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Deleted /LogReg


2022-05-06 14:15:08,846 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-06 14:15:10,729 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-05-06 14:15:12,468 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


CompletedProcess(args=['hdfs', 'dfs', '-put', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/train.csv', '/LogReg/Input'], returncode=0)

In [15]:
subprocess.run(["hdfs", "dfs", "-rm", "-r", f'{HADOOP_PATH}/Output'])

subprocess.run(
    [
        "hadoop",
        "jar", 
        STREAMING_JAR,
        "-file",
        MAPPER_PATH,
        "-file",
        REDUCER_PATH,
        "-input",
        f'{HADOOP_PATH}/Input',
        "-output",
        f'{HADOOP_PATH}/Output',
        "-mapper",
        f'{MAPPER_PATH} {epochs} {alpha}',
        "-reducer",
        f'{REDUCER_PATH}'
    ]
)

2022-05-06 14:15:14,475 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
rm: `/LogReg/Output': No such file or directory
2022-05-06 14:15:16,098 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
2022-05-06 14:15:16,242 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


packageJobJar: [/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py, /home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py, /tmp/hadoop-unjar1246238965075856085/] [] /tmp/streamjob10328717910516916972.jar tmpDir=null


2022-05-06 14:15:17,001 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
2022-05-06 14:15:17,176 INFO client.DefaultNoHARMFailoverProxyProvider: Connecting to ResourceManager at /0.0.0.0:8032
2022-05-06 14:15:17,407 INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/islamahmed1092/.staging/job_1651835008910_0012
2022-05-06 14:15:17,699 INFO mapred.FileInputFormat: Total input files to process : 1
2022-05-06 14:15:17,734 INFO mapreduce.JobSubmitter: number of splits:2
2022-05-06 14:15:17,952 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1651835008910_0012
2022-05-06 14:15:17,952 INFO mapreduce.JobSubmitter: Executing with tokens: []
2022-05-06 14:15:18,120 INFO conf.Configuration: resource-types.xml not found
2022-05-06 14:15:18,120 INFO resource.ResourceUtils: Unable to find 'resource-types.xml'.
2022-05-06 14:15:18,169 INFO impl.YarnClientImpl: Submitted application application_165

CompletedProcess(args=['hadoop', 'jar', '/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.0.jar', '-file', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py', '-file', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py', '-input', '/LogReg/Input', '-output', '/LogReg/Output', '-mapper', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/mapper.py 100 0.001', '-reducer', '/home/islamahmed1092/Desktop/hotel-booking-demand-analysis/LogReg/reducer.py'], returncode=0)

In [16]:
subprocess.run(["hdfs", "dfs", "-cat", f'{HADOOP_PATH}/Output/*'])

2022-05-06 14:16:22,685 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


0,-0.8557708890746714	
1,0.11405748300885006	
10,0.08499580081193367	
11,-0.020261606335308883	
12,0.0719543857423875	
13,0.8469970501724289	
14,0.2068545386329434	
15,0.25604381401082066	
16,-0.15494059840982521	
17,1.716941060743846	
18,-0.5669673909747577	
19,-0.44082069000083945	
2,0.43450457411676224	
20,0.5593389953258794	
21,-0.23562597659409845	
22,1.2635465367535526	
23,0.04426282687869723	
24,-0.044320986374034484	
25,-0.05264507989466281	
26,0.5466642916487978	
27,0.2905671091087319	
28,-2.2581125375201974	
29,-0.46154895231036513	
3,0.2786628317278258	
4,-0.041708555645396564	
5,0.10142220893861836	
6,-0.001543850324260576	
7,0.039663311435341464	
8,0.08301442215261196	
9,0.2740200225882914	


CompletedProcess(args=['hdfs', 'dfs', '-cat', '/LogReg/Output/*'], returncode=0)

In [17]:
subprocess.run(["rm", "-r", f'{os.getcwd()}/Output'])
subprocess.run(["hdfs", "dfs", "-get", f'{HADOOP_PATH}/Output/', os.getcwd()])

subprocess.run(["ls", 'Output'])

2022-05-06 14:16:24,609 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


part-00000
_SUCCESS


CompletedProcess(args=['ls', 'Output'], returncode=0)

In [18]:
out = pd.read_csv('Output/part-00000', header=None, names=["index", "w"])
out = out.sort_values('index').reset_index(drop=True)
out.head()

index         w
0      0 -0.855771
1      1  0.114057
2      2  0.434505
3      3  0.278663
4      4 -0.041709

In [19]:
w = out['w'].to_numpy().reshape(-1, 1)
print(w.shape)

(30, 1)


In [20]:
probs = X_test_aug @ w
predictions = np.where(probs > 0.5, 1, 0)
acc_lr = accuracy_score(y_test, predictions)
conf = confusion_matrix(y_test, predictions)
clf_report = classification_report(y_test, predictions)

print(f"Accuracy Score of Logistic Regression is : {acc_lr}")
print(f"Confusion Matrix : \n{conf}")
print(f"Classification Report : \n{clf_report}")

Accuracy Score of Logistic Regression is : 0.7943860857585673
Confusion Matrix : 
[[21197   951]
 [ 6213  6481]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.77      0.96      0.86     22148
           1       0.87      0.51      0.64     12694

    accuracy                           0.79     34842
   macro avg       0.82      0.73      0.75     34842
weighted avg       0.81      0.79      0.78     34842

